### ISSUE TITLE
Cookie Monster does not work with the latest update, 2.0045.

### ISSUE THREAD

**Issue by Au-Matt** [Aktanusa/CookieMonster#161]

**Comment by Aktanusa** [comment]
Well just like the previous bug, it just came out, I need time to fix.

**Comment by Au-Matt** [comment]
Ok, thanks.

**Comment by ThexXTURBOXx** [comment]
Ehm... It works. There is only 1 warning when loaded.

**Comment by Au-Matt** [comment]
Ok, thanks.

**Comment by KDederichs** [comment]
Seems like it only happens when you ascend and get the new heavenly upgrade, cause it was working for me before I did that and after it broke.

**Comment by ThexXTURBOXx** [comment]
Ah ok, didn't test that... Raising heavenly Chips for the 1 Billion Upgrade right now ;)

**Comment by ThexXTURBOXx** [comment]
After reascending with the new heavenly upgrades bought, I noticed, that there is bug #160 , but no other issues right now

**Comment by Aktanusa** [comment]
Fixed in Version 2.0045.1

**Comment by jacekkopecky** [comment]
please publish 2.0045.1? It's not at https://cdn.rawgit.com/Aktanusa/CookieMonster/dev/CookieMonster.js yet.

**Comment by Aktanusa** [comment]
Dang, it's been a while.  Surprise it's not yet.  Soon.

**Comment by ShimmerFairy** [comment]
Cookie Monster still won't load, using the bookmarklet or userscript code in the README of the repository. It's still pulling the old version of the script.

**Comment by Aktanusa** [comment]
Which is correct.  I've not published it yet.  I'm doing final testing.  Should be soon.

**Comment by Au-Matt** [comment]
Ok, thanks.
