### ISSUE TITLE
Version prompt on every game start

### ISSUE THREAD

**Issue by bannisdale** [Aktanusa/CookieMonster#281]
Hi there,

I am getting this prompt for quite some time now. 

![grafik](https://user-images.githubusercontent.com/42511384/69235434-b13dc400-0b91-11ea-9155-c6e91cc113e2.png)

I load the addon via GreaseMonkey, using https://aktanusa.github.io/CookieMonster/CookieMonster.js
I also tried using to load the addon from https://cdn.rawgit.com/Aktanusa/CookieMonster/dev/CookieMonster.js – same problem.

The game says it's on v. 2.022 in the lower left corner.

I also tried using the beta branch with this, but this just broke the game (after a slightly different prompt).

Is there a way to either get the correct addon version for my game version or at least to get rid of the prompt, as the addon seems to work quite well with the current game version?

Thanks in advance! :)

**Comment by Aktanusa** [comment]
The change from 2.021 to 2.022 was very small that loading 2.021.2 of CM will work fine.  I've already changed the version number but have not released it because I wanted to add more stuff before releasing, but I've been slow to do so.  Sorry about that and please be patient with me.  Basically this is already fixed, but if you really cannot wait, you can load the dev version which already has the fix.

**Comment by bannisdale** [comment]
Like I've written, I already tried the dev branch. In fact, the above-mentioned rawgit url is currently sitting in my userscript to load the resource. I'm still getting the prompt.

I realize that the version is working, but I frequently refresh the page which results in a lot of (unneccesary) prompts that have to be confirmed every single time. :)

**Comment by Aktanusa** [comment]
you wrote you tried the **beta** branch, not the **dev** branch.

**Comment by bannisdale** [comment]
Well, I took the URL from the overview page as it is linked in the "Bugs and suggestions" section there. :)

To be honest, I have no idea how I would force refresh the URL but I tried using https://aktanusa.github.io/CookieMonster/dev/CookieMonster.js instead. This worked for me.

Maybe replace the rawgit URL with the relative one?

Anyway, thanks for the help! I'll close the issue.

**Comment by bannisdale** [comment]
Ooookay, sorry for my stupidity. It didn't work, it just gave me no script at all. :D

So ... which URL should I use instead? Or how do I 'force refresh' the gitraw URL?

**Comment by Aktanusa** [comment]
I would just open a new tab (or page) and go directly to https://cdn.rawgit.com/Aktanusa/CookieMonster/dev/CookieMonster.js.  Then I would press ctrl + F5.  Then do a search in the page and make sure it says '2.022' somewhere in the page.

**Comment by ThexXTURBOXx** [comment]
@Aktanusa No, that is most likely a problem with rawgit, because the service has reached the end of its life. I would suggest using e.g. jsdelivr instead: https://cdn.jsdelivr.net/gh/Aktanusa/CookieMonster@dev/CookieMonster.js

**Comment by Aktanusa** [comment]
Ah, thanks for the heads up!

**Comment by bannisdale** [comment]
Since I couldn't rawgit to work properly, I was about to upload the file to my own webspace, but the JSDelivr url works fine now, thanks @ThexXTURBOXx!

I'll finally close this. Thansk everyone. :D
